export const wordPool: string[] = [
    "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew", "kiwi", "lemon",
    "mango", "nectarine", "orange", "papaya", "quince", "raspberry", "strawberry", "tangerine", "ugli", "vanilla",
    "watermelon", "xigua", "yam", "zucchini", "apricot", "blueberry", "cantaloupe", "dragonfruit", "eucalyptus", "fennel",
    "grapefruit", "honeydew", "kiwi", "lime", "mango", "nectarine", "olive", "plum", "quince", "rhubarb",
    "soursop", "tomato", "ugli", "velvet", "walnut", "xylophone", "yam", "zucchini", "avocado", "blueberry",
    "cucumber", "dandelion", "eggplant", "fennel", "grapefruit", "honeydew", "jicama", "kale", "lemongrass", "mushroom",
    "nectarine", "orange", "peach", "quince", "rhubarb", "spinach", "tomato", "umbrella", "violet", "watermelon",
    "xigua", "yam", "zucchini", "antelope", "butterfly", "caterpillar", "dolphin", "elephant", "flamingo", "giraffe",
    "hippopotamus", "iguana", "jaguar", "kangaroo", "lemur", "monkey", "nightingale", "octopus", "penguin", "quail",
    "rhinoceros", "snake", "tiger", "unicorn", "vulture", "wolf", "xylophone", "yak", "zebra", "albatross",
    "buffalo", "crab", "dragonfly", "emu", "falcon", "goose", "heron", "ibis", "jackal", "koala",
    "lizard", "meerkat", "newt", "octopus", "parrot", "quokka", "raven", "seagull", "turtle", "urchin",
    "viper", "weasel", "xenops", "yak", "zebu", "ant", "bee", "caterpillar", "dung", "earthworm",
    "firefly", "grasshopper", "hopper", "insect", "jellyfish", "knot", "leech", "moth", "nymph", "owl",
    "pupa", "quartz", "reptile", "silkworm", "termite", "urchin", "vampire", "wildebeest", "xerox", "yogi",
    "zodiac", "angler", "barracuda", "clownfish", "dolphin", "eel", "flounder", "grouper", "herring", "iago",
    "jellyfish", "kelp", "lobster", "mahi-mahi", "nemo", "octopus", "pufferfish", "quahog", "ray", "shark",
    "tuna", "urchin", "viperfish", "whale", "xiphias", "yellowtail", "zander", "algae", "barracuda", "crab",
    "donut", "eclair", "fritter", "gelato", "honey", "icecream", "jalapeno", "kiwi", "lemonade", "macaron",
    "nougat", "orange", "pancake", "quiche", "raspberry", "scone", "tart", "udon", "vanilla", "waffle",
    "xylocarp", "yogurt", "zabaglione", "artichoke", "broccoli", "cabbage", "dandelion", "endive", "fennel", "garlic",
    "honeydew", "jalapeno", "kale", "lettuce", "mushroom", "napa", "onion", "parsley", "quinoa", "rhubarb",
    "spinach", "tomato", "uvas", "vinegar", "watercress", "xanthium", "yam", "zucchini", "asparagus", "beetroot",
    "cauliflower", "daikon", "eggplant", "fennel", "gourd", "horseradish", "kohlrabi", "leek", "mangetout", "nori",
    "okra", "peppers", "quince", "rhubarb", "salsify", "taro", "udon", "vegetable", "wasabi", "yarrow", "zucchini",
    "almond", "bean", "cashew", "date", "edamame", "flaxseed", "grape", "hazelnut", "iceberg", "jalapeno",
    "kalamata", "lemon", "mango", "nectar", "orange", "pomegranate", "quince", "rose", "starfruit", "tangerine",
    "umbrella", "velvet", "watercress", "xanadu", "yellowfruit", "zebra", "aero", "blender", "carrot", "device",
    "eggplant", "firewood", "grape", "hammer", "ice", "juice", "kettle", "lemonade", "maple", "noodle",
    "octopus", "paper", "quartz", "robot", "scooter", "topaz", "umbrella", "vacuum", "whisk", "xylophone",
    "yarn", "zebra", "alphabet", "book", "cup", "dice", "eagle", "frog", "glove", "house", "ink",
    "jug", "key", "lamp", "mouse", "necklace", "orange", "pen", "quilt", "ring", "sock", "table",
    "umbrella", "vase", "watch", "xylophone", "yogurt", "zebra", "apron", "bat", "candle", "drawer", "envelope",
    "flag", "glue", "hat", "ice", "jar", "kettle", "laptop", "magnet", "nut", "owl", "pencil",
    "quill", "ruler", "scissors", "towel", "umbrella", "vase", "window", "xylophone", "yogurt", "zebra"
];

export const punctuationMarks: string[] = [".", ",", "!", "?", ";", ":"];